---

- name: Install dhcp client packages
  apt: pkg='{{item}}' state=present cache_valid_time=3600 install_recommends=no
  with_items:
    - isc-dhcp-client
    - bind9-host

- name: Copy dhcp hostname script to exit hook
  copy: src={{item}} dest=/{{item}} mode=0755 owner=root group=root
  with_items:
    - etc/dhcp/dhclient-exit-hooks.d/hostname

- name: Link hostname to default network interface
  file:
    dest=/etc/dhcp/dhclient-exit-hooks.d/hostname-{{ansible_default_ipv4.interface}}
    src=hostname
    state=link
